export const MEDICAL_CONDITIONS_LIST = [
  "High Blood Pressure",
  "Low Blood Pressure",
  "Epilepsy or Convulsion",
  "AIDS or HIV Infection",
  "Sexually Transmitted Disease",
  "Stomach Troubles or Ulcers",
  "Fainting Seizures",
  "Rapid Weight Loss",
  "Radiation Therapy",
  "Joint Replacement or Implant",
  "Heart Surgery",
  "Heart Attack",
  "Heart Disease",
  "Heart Murmur",
  "Hepatitis or Liver Disease",
  "Rheumatic Fever",
  "Allergies",
  "Respiratory Problems",
  "Tuberculosis",
  "Gout or Swollen Ankles",
  "Kidney Disease",
  "Chest Pain",
  "Stroke",
  "Cancer or Tumors",
  "Anemia",
  "Angina",
  "Asthma",
  "Bleeding Problems",
  "Emphysema",
  "Head Injuries",
  "Arthritis or Rheumatism",
  "Thyroid Problem",
  "Diabetes"
];

export const DENTAL_HABITS_LIST = [
  "night time bottle feeding",
  "thumb sucking",
  "tongue thrusting",
  "teeth grinding",
  "nail biting",
  "mouth breathing",
  "smoking"
];
